import type { Product, ProductDTO } from "../model/Product";

export const toProduct = (dto: ProductDTO): Product => ({
  id: dto.id,
  title: dto.title,
  description: dto.description,
  category: dto.category,
  price: dto.price,
  discountPercentage: dto.discountPercentage,
  rating: dto.rating ?? 0,
  stock: dto.stock,
  tags: dto.tags,
  brand: dto.brand ?? "Unknown",
  sku: dto.sku,
  weight: dto.weight,
  dimensions: dto.dimensions,
  warrantyInformation: dto.warrantyInformation,
  shippingInformation: dto.shippingInformation,
  availabilityStatus: dto.availabilityStatus,
  reviews: dto.reviews,
  returnPolicy: dto.returnPolicy,
  minimumOrderQuantity: dto.minimumOrderQuantity,
  meta: dto.meta,
  thumbnail: dto.thumbnail,
  images: dto.images,
});
